version: '3.7'

services:
  gcp-provisioner:
    image: gcp-provisioner
    build:
      context: .
      dockerfile: Dockerfile
      target: gcp-provisioner
    working_dir: /local
    volumes:
      - ./../:/local/
      - $HOME/.config/zsh:/root/.config/zsh

